### ISSUE TITLE
Skip download of dependency if already exists

### ISSUE THREAD

**Issue by cdbartholomew** [LangStream/langstream#189] opened 2023-08-09 19:56 UTC
It appears that the download of a dependency is always done even if the file is already present. Since we have a checksum for the download, we should check that the file exists and it matches the checksum. If it matches, then the download can be skipped. This can save time when iterating on a new pipeline. Having to download a large Kafka connector can be slow.

**Comment by nicoloboschi** [comment] 2023-08-21 08:41
@cdbartholomew not able to reproduce with the latest cli version. would you mind to test it again ? maybe I fixed it already

**Comment by nicoloboschi** [comment] 2023-08-30 09:45
Fixed with latest version

**Closed as completed by nicoloboschi** 2023-08-30 09:45 UTC
